In [1]:
import pandas as pd,numpy as np
import re,joblib,json
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import classification_report,accuracy_score

# Load Data

In [2]:
df=pd.read_csv("Data/course_dataset_1000.csv")
df.head()

,Interest,Career Goal,Skills,Course
0,Engineering,Automobile Engineer,Physics;Design,Mechanical Engineering
1,Medical,Staff Nurse,Patient Care;Biology,BSc Nursing
2,Medical,Pharma Researcher,Chemistry;Medicine,BPharmacy
3,Engineering,Control Engineer,Automation;Math,Electrical Engineering
4,Engineering,Electrical Engineer,Automation;Math,Electrical Engineering

In [3]:
df1=pd.read_csv("Data/course_dataset_100.csv")
df1.head()

,Interest,Career Goal,Skills,Recommended Course,Stream,GPA
0,Arts,Counselor,Writing;Problem Solving,BA Psychology,Management,3.41
1,Engineering,Power Engineer,Circuits;Analysis,Electrical Engineering,Science,3.45
2,Business,Brand Manager,Communication;Creativity,BBM,Management,3.67
3,IT,Network Engineer,Networking;Problem Solving,Computer Engineering,Science,2.93
4,IT,Network Engineer,Coding;Logic,Computer Engineering,Science,3.72

In [4]:
df2=pd.read_csv("Data/nepal_course_recommendation_dataset_100.csv")
df2.head()

,Student_ID,Interest,Career Goal,Skills,Recommended Course
0,S001,IT,Software Developer,"Coding, Logic, Problem Solving",BCA
1,S002,Computers,Web Developer,"Creativity, Coding, Basic Math",BCA
2,S003,Web Development,IT Support Engineer,"Coding, Creativity, Basic Math",BCA
3,S004,Computers,Web Developer,"Basic Math, Creativity, Coding",BCA
4,S005,Web Development,Web Developer,"Creativity, Basic Math, Debugging",BCA

In [5]:
df3=pd.read_csv("Data/original_course_dataset.csv")
df3.head()

  Interest        Career Goal                       Skills Course
0       IT          Developer                 Coding;Logic    BCA
1       IT  Software Engineer  Programming;Problem Solving    BCA
2       IT      Web Developer                  HTML;CSS;JS    BCA
3       IT      App Developer                 Java;Android    BCA
4       IT         Programmer             Coding;Debugging    BCA

In [6]:
df4=pd.read_csv("Data/dataset_191.csv")

In [7]:
df4.head(2)

    Interest         Career Goal                          Skills Course
0         IT  Software Developer  Coding, Logic, Problem Solving    BCA
1  Computers       Web Developer  Creativity, Coding, Basic Math    BCA

In [8]:
df5=pd.read_csv("Data/Interest,CareerGoal,Skills,Course.csv")

In [9]:
df5.head(25)

,Interest,CareerGoal,Skills,Course
0,Automotive Design,Mechanical Engineer,"CAD, Thermodynamics, MATLAB",Mechanical Engineering
1,Patient Care,Registered Nurse,"Empathy, Clinical Assessment, Wound Care",BSc Nursing
2,Drug Formulation,Pharmacist,"Pharmacology, Inventory Management, Attention ...",BPharmacy
3,Circuit Design,Electrical Engineer,"Circuit Design, PLC, Troubleshooting",Electrical Engineering
4,Bridge Construction,Civil Engineer,"Structural Analysis, STAAD Pro, Project Manage...",Civil Engineering
5,Strategic Management,Business Development Manager,"Leadership, Financial Accounting, Excel",BBM
6,News Reporting,Journalist,"Copy Editing, Video Editing, Interviewing",BJMC
7,Cognitive Behavior Therapy,Clinical Psychologist,"Active Listening, SPSS, Case Documentation",BA Psychology
8,Financial Analysis,Financial Analyst,"Tally, Taxation, Data Analysis",BBS
9,Cardiology,Cardiologist,"Clinical Diagnosis, ECG Interpretation, Bedsid...",MBBS
10,Network Security,Network Administrator,"Linux, Cybersecurity, Cloud Computing",BIT
11,Brand Marketing,Marketing Manager,"Branding, P&L Management, Digital Marketing",BBA
12,Hotel Operations,Hotel General Manager,"Front Office, F&B Control, Guest Relations",BHM
13,Embedded Systems,Firmware Engineer,"C++, Microcontrollers, Digital Logic",Computer Engineering
14,Web Development,Full Stack Developer,"Java, Python, React, MySQL",BCA
15,Social Research,NGO Project Coordinator,"Survey Design, Report Writing, Advocacy",BA Sociology
16,Data Science,Data Scientist,"Python, Machine Learning, Statistics, SQL",BSc CSIT
17,Corporate Law,Corporate Lawyer,"Legal Drafting, Negotiation, Contract Law",BALLB
18,Thermal Engineering,Thermal Engineer,"CFD, ANSYS, Heat Transfer",Mechanical Engineering
19,Pediatric Care,Pediatric Nurse,"Child Health Assessment, Immunization, Communi...",BSc Nursing
20,Pharmaceutical Research,Drug Discovery Scientist,"Medicinal Chemistry, HPLC, GLP",BPharmacy
21,Power Systems,Power Systems Engineer,"ETAP, Relay Coordination, SCADA",Electrical Engineering
22,Highway Design,Transportation Engineer,"AutoCAD Civil 3D, Traffic Analysis, Surveying",Civil Engineering
23,Human Resources,HR Manager,"Recruitment, Employee Relations, Labor Law",BBM
24,Digital Media,Content Strategist,"SEO, Social Media Management, Analytics",BJMC

In [10]:
df6=pd.read_csv("Data/career_dataset.csv")

In [11]:
df6.head(2)

,Interest,CareerGoal,Skills,Course
0,Automobile Design,Automotive Engineer,"CAD, Thermodynamics, Problem Solving",Mechanical Engineering
1,Robotics,Robotics Engineer,"Mechanics, Programming, Math",Mechanical Engineering

In [12]:
df6[df6['Course']=='BA']

,Interest,CareerGoal,Skills,Course
90,English Literature,Content Writer,"Writing, Editing, Creativity",BA
91,History,Archivist,"Research, Organization, Attention to Detail",BA
92,Political Science,Policy Analyst,"Critical Thinking, Data Analysis, Writing",BA
93,Economics,Economic Consultant,"Quantitative Analysis, Econometrics, Excel",BA
94,Philosophy,Ethics Advisor,"Logical Reasoning, Debate, Writing",BA

In [13]:
df7=pd.read_csv("Data/c-dataset_500.csv")

In [14]:
df7.head(10)

,Interest,Career Goal,Skills,Course
0,Hotel front office and housekeeping,Hotel Manager or Hospitality professional,"Tourism marketing, travel itinerary planning",BHM
1,Clinical pharmacy and patient counseling,Regulatory Affairs Specialist,"Regulatory compliance, FDA/EMA guidelines",BPharmacy
2,Robotics and automation hardware,VLSI Design Engineer,"IoT protocols, sensor integration",Computer Engineering
3,Human resource development,Startup Founder or CEO,"Digital marketing, social media management",BBM
4,Robotics and industrial automation,Embedded Systems Engineer in robotics,"MATLAB, Simulink, PLC programming",Electrical Engineering
5,Cloud computing and DevOps,Cloud Engineer in IT services,"SQL, MongoDB, API development",BCA
6,"Computer hardware, software integration and em...",Embedded Systems Engineer in IoT,"Microprocessor design, circuit simulation",Computer Engineering
7,Transportation and highway engineering,Transportation Engineer in public works,"STAAD Pro, ETABS, BIM software",Civil Engineering
8,"Pharmaceuticals, drug formulation and dispensing",Medical Representative or sales executive in p...,"Quality assurance, GMP standards, lab testing",BPharmacy
9,Web technologies and software engineering,Data Analyst or Business Intelligence Developer,"Software engineering, agile development",BSc CSIT

In [ ]:
df8=pd.read_csv("Data/ba.csv")

In [16]:
df8.head(2)

,Interest,Career Goal,Skills,Course
0,Urban Studies,Community Development Officer,"Community Outreach, Grant Writing, Qualitative...",BA Sociology
1,Criminology,Juvenile Probation Officer,"Case Management, Conflict Resolution, Report W...",BA Sociology

# Data Preprocessing

## For df1

In [17]:
df1['Course']=df1["Recommended Course"]

In [18]:
df1.drop(columns=["Recommended Course","Stream","GPA"],inplace=True)

In [19]:
df1.head(5)

,Interest,Career Goal,Skills,Course
0,Arts,Counselor,Writing;Problem Solving,BA Psychology
1,Engineering,Power Engineer,Circuits;Analysis,Electrical Engineering
2,Business,Brand Manager,Communication;Creativity,BBM
3,IT,Network Engineer,Networking;Problem Solving,Computer Engineering
4,IT,Network Engineer,Coding;Logic,Computer Engineering

## For df2

In [20]:
df2['Course']=df2['Recommended Course']

In [21]:
df2.drop(columns=['Student_ID','Recommended Course'],inplace=True)

In [22]:
df2.head(5)

,Interest,Career Goal,Skills,Course
0,IT,Software Developer,"Coding, Logic, Problem Solving",BCA
1,Computers,Web Developer,"Creativity, Coding, Basic Math",BCA
2,Web Development,IT Support Engineer,"Coding, Creativity, Basic Math",BCA
3,Computers,Web Developer,"Basic Math, Creativity, Coding",BCA
4,Web Development,Web Developer,"Creativity, Basic Math, Debugging",BCA

## df5

In [23]:
df5['Career Goal']=df5['CareerGoal']

In [24]:
df5.drop('CareerGoal',axis='columns',inplace=True)

## For df6

In [25]:
df6['Career Goal']=df6['CareerGoal']

In [26]:
df6.drop('CareerGoal',axis='columns',inplace=True)

In [27]:
df6.head(2)

,Interest,Skills,Course,Career Goal
0,Automobile Design,"CAD, Thermodynamics, Problem Solving",Mechanical Engineering,Automotive Engineer
1,Robotics,"Mechanics, Programming, Math",Mechanical Engineering,Robotics Engineer

## For df7

In [28]:
for col in df7.columns:
    df7[col] = df7[col].str.replace(r'\b(and|or)\b', ',', regex=True, flags=re.IGNORECASE)

In [29]:
df7.head(5)

,Interest,Career Goal,Skills,Course
0,"Hotel front office , housekeeping","Hotel Manager , Hospitality professional","Tourism marketing, travel itinerary planning",BHM
1,"Clinical pharmacy , patient counseling",Regulatory Affairs Specialist,"Regulatory compliance, FDA/EMA guidelines",BPharmacy
2,"Robotics , automation hardware",VLSI Design Engineer,"IoT protocols, sensor integration",Computer Engineering
3,Human resource development,"Startup Founder , CEO","Digital marketing, social media management",BBM
4,"Robotics , industrial automation",Embedded Systems Engineer in robotics,"MATLAB, Simulink, PLC programming",Electrical Engineering

## Combining all Dataframes

In [30]:
len(df)

1000

In [31]:
len(df1)

100

In [32]:
len(df2)

100

In [33]:
len(df3)

90

In [34]:
len(df4)

192

In [35]:
len(df5)

183

In [36]:
len(df6)

95

In [37]:
len(df7)

500

In [38]:
len(df8)

11

In [39]:
big_df=pd.concat([df,df1,df2,df3,df4,df5,df6,df7,df8],ignore_index=True)

In [40]:
big_df.head(2)

,Interest,Career Goal,Skills,Course
0,Engineering,Automobile Engineer,Physics;Design,Mechanical Engineering
1,Medical,Staff Nurse,Patient Care;Biology,BSc Nursing

In [41]:
len(big_df)

2271

In [42]:
big_df.iloc[1000:1002]

,Interest,Career Goal,Skills,Course
1000,Arts,Counselor,Writing;Problem Solving,BA Psychology
1001,Engineering,Power Engineer,Circuits;Analysis,Electrical Engineering

In [43]:
big_df.iloc[1100:1102]

       Interest         Career Goal                          Skills Course
1100         IT  Software Developer  Coding, Logic, Problem Solving    BCA
1101  Computers       Web Developer  Creativity, Coding, Basic Math    BCA

In [44]:
big_df.iloc[1200:1202]

     Interest        Career Goal                       Skills Course
1200       IT          Developer                 Coding;Logic    BCA
1201       IT  Software Engineer  Programming;Problem Solving    BCA

In [45]:
big_df.iloc[1290:1295]

,Interest,Career Goal,Skills,Course
1290,IT,Software Developer,"Coding, Logic, Problem Solving",BCA
1291,Computers,Web Developer,"Creativity, Coding, Basic Math",BCA
1292,Web Development,IT Support Engineer,"Coding, Creativity, Basic Math",BCA
1293,Computers,Web Developer,"Basic Math, Creativity, Coding",BCA
1294,Web Development,Web Developer,"Creativity, Basic Math, Debugging",BCA

## Replacing ; into ,

In [46]:
big_df['Skills'] = big_df['Skills'].str.replace(';', ',')

In [47]:
big_df.head(2)

,Interest,Career Goal,Skills,Course
0,Engineering,Automobile Engineer,"Physics,Design",Mechanical Engineering
1,Medical,Staff Nurse,"Patient Care,Biology",BSc Nursing

## mapping

In [48]:
big_df['Course'].unique()

array(['Mechanical Engineering', 'BSc Nursing', 'BPharmacy',
       'Electrical Engineering', 'Civil Engineering', 'BBM', 'BJMC',
       'BA Psychology', 'BBS', 'MBBS', 'BIT', 'BBA', 'BHM',
       'Computer Engineering', 'BCA', 'BA Sociology', 'BSc CSIT', 'BALLB',
       'BA'], dtype=object)

In [49]:
budget_map = {
    "MBBS": "High",
    "Mechanical Engineering": "High",
    "Civil Engineering": "High",
    "Computer Engineering": "High",
    "Electrical Engineering": "High",
    "BSc Nursing": "High",

    "BPharmacy": "Mid",
    "BBM": "Mid",
    "BALLB": "Mid",
    "BCA": "Mid",
    "BIT": "Mid",
    "BBA": "Mid",
    "BHM": "Mid",
    "BSc CSIT": "Mid",
    "BJMC": "Mid",
    "BA Psychology": "Mid",


    "BBS": "Low",
    "BA Sociology": "Low",
}

## creating new column

In [50]:
big_df["Budget"] = big_df["Course"].map(budget_map)

In [51]:
big_df.head(2)

,Interest,Career Goal,Skills,Course,Budget
0,Engineering,Automobile Engineer,"Physics,Design",Mechanical Engineering,High
1,Medical,Staff Nurse,"Patient Care,Biology",BSc Nursing,High

## checking Null value

In [52]:
big_df.isnull().sum()

Interest        0
Career Goal     0
Skills          0
Course          0
Budget         11
dtype: int64

In [53]:
big_df['Budget'].isnull().any()

np.True_

## Extracting NULL rows

In [54]:
big_df[big_df['Budget'].isnull()]

,Interest,Career Goal,Skills,Course,Budget
1194,History,Teacher,"Analysis, Reading, Presentation",BA,NaN
1195,History,Researcher,"Reading, Critical Thinking, Analysis",BA,NaN
1196,Literature,Writer,"Communication, Critical Thinking, Presentation",BA,NaN
1197,History,Writer,"Presentation, Analysis, Reading",BA,NaN
1198,Journalism,Public Service Staff,"Writing, Reading, Presentation",BA,NaN
1199,Social Science,Researcher,"Presentation, Analysis, Reading",BA,NaN
1755,English Literature,Content Writer,"Writing, Editing, Creativity",BA,NaN
1756,History,Archivist,"Research, Organization, Attention to Detail",BA,NaN
1757,Political Science,Policy Analyst,"Critical Thinking, Data Analysis, Writing",BA,NaN
1758,Economics,Economic Consultant,"Quantitative Analysis, Econometrics, Excel",BA,NaN
1759,Philosophy,Ethics Advisor,"Logical Reasoning, Debate, Writing",BA,NaN

## BA course row index

In [55]:
idx = big_df[big_df['Course']== 'BA'].index

In [56]:
big_df.loc[idx]

,Interest,Career Goal,Skills,Course,Budget
1194,History,Teacher,"Analysis, Reading, Presentation",BA,NaN
1195,History,Researcher,"Reading, Critical Thinking, Analysis",BA,NaN
1196,Literature,Writer,"Communication, Critical Thinking, Presentation",BA,NaN
1197,History,Writer,"Presentation, Analysis, Reading",BA,NaN
1198,Journalism,Public Service Staff,"Writing, Reading, Presentation",BA,NaN
1199,Social Science,Researcher,"Presentation, Analysis, Reading",BA,NaN
1755,English Literature,Content Writer,"Writing, Editing, Creativity",BA,NaN
1756,History,Archivist,"Research, Organization, Attention to Detail",BA,NaN
1757,Political Science,Policy Analyst,"Critical Thinking, Data Analysis, Writing",BA,NaN
1758,Economics,Economic Consultant,"Quantitative Analysis, Econometrics, Excel",BA,NaN
1759,Philosophy,Ethics Advisor,"Logical Reasoning, Debate, Writing",BA,NaN

## Removing BA row

In [57]:
big_df = big_df.drop(idx)

## Checking any null value left

In [58]:
big_df.isnull().sum()

Interest       0
Career Goal    0
Skills         0
Course         0
Budget         0
dtype: int64

In [59]:
big_df[big_df['Budget'].isnull()]

Empty DataFrame
Columns: [Interest, Career Goal, Skills, Course, Budget]
Index: []

## checking Duplicates

In [60]:
big_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2266    False
2267    False
2268    False
2269    False
2270    False
Length: 2260, dtype: bool

In [61]:
big_df.duplicated().sum()

np.int64(787)

In [62]:
duplicate_rows = big_df[big_df.duplicated(keep=False)]

In [63]:
duplicate_rows

,Interest,Career Goal,Skills,Course,Budget
0,Engineering,Automobile Engineer,"Physics,Design",Mechanical Engineering,High
1,Medical,Staff Nurse,"Patient Care,Biology",BSc Nursing,High
2,Medical,Pharma Researcher,"Chemistry,Medicine",BPharmacy,Mid
3,Engineering,Control Engineer,"Automation,Math",Electrical Engineering,High
4,Engineering,Electrical Engineer,"Automation,Math",Electrical Engineering,High
...,...,...,...,...,...
2239,"International business , trade",Operations Manager in manufacturing/retail,"Business planning, SWOT analysis, strategy for...",BBM,Mid
2241,"International business , trade",Financial Analyst in banking sector,"Human resource planning, recruitment, training",BBM,Mid
2246,"Artificial intelligence , machine learning",Full Stack Developer,"SQL, NoSQL, big data tools (Hadoop/Spark)",BSc CSIT,Mid
2251,"Environmental , family law","Criminal Lawyer , Public Prosecutor","Drafting legal documents, litigation skills",BALLB,Mid
2253,"Advertising , corporate communication","Social Media Manager , Content Creator","Broadcast journalism, script writing",BJMC,Mid

## Removing duplicates

In [64]:
big_df.drop_duplicates(inplace=True)

In [65]:
big_df.duplicated().sum()

np.int64(0)

In [66]:
len(big_df)

1473

## Checking Class Balance

In [67]:
df['Course'].value_counts()

Course
Mechanical Engineering    56
BSc Nursing               56
BPharmacy                 56
Electrical Engineering    56
Civil Engineering         56
MBBS                      56
BCA                       56
BSc CSIT                  56
Computer Engineering      56
BIT                       56
BBS                       55
BA Psychology             55
BJMC                      55
BBM                       55
BHM                       55
BBA                       55
BA Sociology              55
BALLB                     55
Name: count, dtype: int64

## Convert to String , Lowercase and Remove spaces

In [68]:
for col in ['Interest', 'Career Goal', 'Skills']:
    big_df[col] = big_df[col].astype(str).str.lower().str.strip()

In [69]:
big_df.head(3)

,Interest,Career Goal,Skills,Course,Budget
0,engineering,automobile engineer,"physics,design",Mechanical Engineering,High
1,medical,staff nurse,"patient care,biology",BSc Nursing,High
2,medical,pharma researcher,"chemistry,medicine",BPharmacy,Mid

# Feature selection

## Encoding Target

In [70]:
le = LabelEncoder()
big_df['Course_Encoded'] = le.fit_transform(big_df['Course'])

In [71]:
big_df.head(3)

,Interest,Career Goal,Skills,Course,Budget,Course_Encoded
0,engineering,automobile engineer,"physics,design",Mechanical Engineering,High,17
1,medical,staff nurse,"patient care,biology",BSc Nursing,High,12
2,medical,pharma researcher,"chemistry,medicine",BPharmacy,Mid,10

## Target Fetch

In [72]:
y=big_df['Course_Encoded']

In [73]:
y.head(2)

0    17
1    12
Name: Course_Encoded, dtype: int64

## Features fetch

In [74]:
big_df['combined_text'] = big_df['Interest'] + " " +big_df['Career Goal'] + " " + big_df['Skills']

In [75]:
x=big_df[['combined_text', 'Budget']]

In [76]:
x.head(2)

                                    combined_text Budget
0  engineering automobile engineer physics,design   High
1        medical staff nurse patient care,biology   High

## Checking shapes

In [77]:
x.shape

(1473, 2)

In [78]:
y.shape

(1473,)

## Train Test Split

In [79]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

In [80]:
x_test.shape

(295, 2)

In [81]:
x_train.shape

(1178, 2)

# Features Preprocessing

In [82]:
budget_order = ['Low', 'Mid', 'High']

## Preprocessor

In [83]:
preprocessor = ColumnTransformer(
    transformers=[
        # Ordinal Encoding for Budget 
        ('budget_ord', OrdinalEncoder(categories=[budget_order]), ['Budget']),
        
        ('text_tfidf', TfidfVectorizer(ngram_range=(1, 3), max_features=2500), 'combined_text')  
    ]
)

# Model Creation

In [84]:
model = RandomForestClassifier(
    n_estimators=150,     
    max_depth=12, 
    min_samples_leaf=3,         
    random_state=42       
)

## Using Pipeline

In [85]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

## Model Training

In [86]:
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('budget_ord',
                                                  OrdinalEncoder(categories=[['Low',
                                                                              'Mid',
                                                                              'High']]),
                                                  ['Budget']),
                                                 ('text_tfidf',
                                                  TfidfVectorizer(max_features=2500,
                                                                  ngram_range=(1,
                                                                               3)),
                                                  'combined_text')])),
                ('model',
                 RandomForestClassifier(max_depth=12, min_samples_leaf=3,
                                        n_estimators=150, random_state=42))])

# Model Tuning

## Parameter defining

In [87]:
param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [10, 15, 20],
    'preprocessor__text_tfidf__max_features': [1500, 2500]
}

## Creating GridSearchCV instance

In [88]:
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

## Training & searching multiple models

In [89]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('budget_ord',
                                                                         OrdinalEncoder(categories=[['Low',
                                                                                                     'Mid',
                                                                                                     'High']]),
                                                                         ['Budget']),
                                                                        ('text_tfidf',
                                                                         TfidfVectorizer(max_features=2500,
                                                                                         ngram_range=(1,
                                                                                                      3)),
                                                                         'combined_text')])),
                                       ('model',
                                        RandomForestClassifier(max_depth=12,
                                                               min_samples_leaf=3,
                                                               n_estimators=150,
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [10, 15, 20],
                         'model__n_estimators': [100, 200],
                         'preprocessor__text_tfidf__max_features': [1500,
                                                                    2500]},
             scoring='accuracy')

## Getting best model

In [90]:
best_pipeline = grid_search.best_estimator_

## Best score

In [91]:
print(f"Best Accuracy: {grid_search.best_score_}")

Best Accuracy: 0.8531518211323477

# Model Evaluation

## Calculating Scores

### Normal pipeline

In [92]:
y_pred =pipeline.predict(x_test)
y_train_pred =pipeline.predict(x_train)

In [93]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_pred)

In [94]:
train_acc

0.898981324278438

In [95]:
test_acc

0.8305084745762712

### Best pipeline

In [96]:
yb_pred = best_pipeline.predict(x_test)
yb_train_pred =best_pipeline.predict(x_train)

In [97]:
btrain_acc = accuracy_score(y_train, yb_train_pred)
btest_acc = accuracy_score(y_test, yb_pred)

In [98]:
btrain_acc

0.9108658743633277

In [99]:
btest_acc

0.8508474576271187

In [100]:
# Step 1: Input
my_data = pd.DataFrame({
    'Interest': ['IT'],
    'Career Goal': ['Web developer'],
    'Skills': ['coding'],
    'Budget': ['Mid']
})


my_data['combined_text'] = my_data['Interest'] + " " + my_data['Career Goal'] + " " + my_data['Skills']

# Step 2: Predict
prediction = best_pipeline.predict(my_data)

# Step 3: Decode
final_course = le.inverse_transform(prediction)

print(final_course)

['BCA']

## Extracting Probabilities

In [101]:
probs =best_pipeline.predict_proba(my_data)

## Changing it in 1d

In [102]:
probs = probs[0]

In [103]:
probs

array([0.02663124, 0.01574244, 0.01602012, 0.01986158, 0.02258937,
       0.01844136, 0.44425136, 0.01901306, 0.12653116, 0.02109974,
       0.02415953, 0.11880972, 0.00849165, 0.01297475, 0.06256976,
       0.01038482, 0.02065658, 0.01177177])

## Extract indices of top 3 courses

In [104]:
top3_idx = np.argsort(probs)[-3:][::-1]

In [105]:
top3_idx

array([ 6,  8, 11])

## Decoding Indices into course names

In [106]:
top3_courses = le.inverse_transform(top3_idx)

In [107]:
top3_courses

array(['BCA', 'BIT', 'BSc CSIT'], dtype=object)

## Probabilities of courses

In [108]:
top3_probs = probs[top3_idx]

In [109]:
top3_probs

array([0.44425136, 0.12653116, 0.11880972])

## displaying courses with probability

In [110]:
for course, prob in zip(top3_courses, top3_probs):
    print(f"{course} → {prob:.2f}")

BCA → 0.44
BIT → 0.13
BSc CSIT → 0.12

# Saving Best Model

In [111]:
joblib.dump(best_pipeline, 'course_recommender_Rf.pkl')

['course_recommender_Rf.pkl']

In [112]:
joblib.dump(le, 'label_encoder.pkl')

['label_encoder.pkl']

# Json File for frontend

## Defining the columns

In [113]:
categories = ['Interest', 'Career Goal', 'Skills']
suggestions_data = {}

## Extracting data from columns

In [114]:

for col in categories:
    suggestions_data[col.lower()] = {
        "all": big_df[col].unique().tolist(),
        "top": big_df[col].value_counts().head(5).index.tolist()
    }

## Saving json file

In [115]:
with open('suggestions.json', 'w') as f:
    json.dump(suggestions_data, f)